src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Volunteer_Hours__c</fullName>
        <inlineHelpText>Total number of Hours that are Completed. Hours with other status values are not included.</inlineHelpText>
        <label>Volunteer Hours</label>
        <summarizedField>Volunteer_Hours__c.Hours_Worked__c</summarizedField>
        <summaryFilterItems>
            <field>Volunteer_Hours__c.Status__c</field>
            <operation>equals</operation>
            <value>Completed</value>
        </summaryFilterItems>
        <summaryForeignKey>Volunteer_Hours__c.Contact__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volunteer_Hours__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Hours_Worked__c</fullName>
        <label>Hours Worked</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No-Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Sign Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Volunteer_Shift__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Volunteer Shift</label>
        <referenceTo>Volunteer_Shift__c</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Hours</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>HoursID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volunteer_Job__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Volunteer Jobs</relationshipLabel>
        <relationshipName>Volunteer_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Job</label>
    <nameField>
        <label>Volunteer Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volunteer_Shift__c.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <inlineHelpText>How many hours long is the shift?</inlineHelpText>
        <label>Duration (Hours)</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date &amp; Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipLabel>Volunteer Shifts</relationshipLabel>
        <relationshipName>Volunteer_Job_Slots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Shift</label>
    <nameField>
        <displayFormat>Shift-{00000}</displayFormat>
        <label>ShiftID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VOL_TEST_AutoCompleter.cls
@isTest
public class TestAutoCompleter {
    public static String CRON_EXP = '0 0 0 15 3 ? 2022';
 
    @testSetup public static void create_records() {
        Contact c = new Contact(FirstName='David',LastName='Habib');
        insert c;
        
        Campaign v = new Campaign(Name='Volunteering', IsActive=true);
        insert v;

        Volunteer_Job__c job1 = new Volunteer_Job__c(Name='Work', Campaign__c = v.Id);
        insert job1;
        
        Volunteer_Shift__c pastShift = new Volunteer_Shift__c(Start_Date_Time__c = DateTime.now().addDays(-10), Volunteer_Job__c = job1.Id, Duration__c = 2);
        Volunteer_Shift__c futureShift = new Volunteer_Shift__c(Start_Date_Time__c = DateTime.now().addDays(10), Volunteer_Job__c = job1.Id, Duration__c = 2);
        insert new List<Volunteer_Shift__c> {pastShift, futureShift};
        
        Date pastShiftStartDate = Date.newInstance(pastShift.Start_Date_Time__c.year(), pastShift.Start_Date_Time__c.month(), pastShift.Start_Date_Time__c.day());
        Date futureShiftStartDate = Date.newInstance(futureShift.Start_Date_Time__c.year(), futureShift.Start_Date_Time__c.month(), futureShift.Start_Date_Time__c.day());
        
        List<Volunteer_Hours__c> hoursToInsert = new List<Volunteer_Hours__c>();
        // this record sets a baseline of 20 completed hours
        hoursToInsert.add(new Volunteer_Hours__c(Contact__c = c.Id, Start_Date__c = pastShiftStartDate, Volunteer_Job__c = job1.Id, Status__c = 'Completed', Hours_Worked__c  = 20));

        // this record tests updates not overriding the Hours Worked
        hoursToInsert.add(new Volunteer_Hours__c(Contact__c = c.Id, Volunteer_Job__c = job1.Id, Start_Date__c = pastShiftStartDate, Volunteer_Shift__c = pastShift.Id, Status__c = 'Confirmed', Hours_Worked__c  = 3));

        // this record tests the hours sets to duration rule
        hoursToInsert.add(new Volunteer_Hours__c(Contact__c = c.Id, Volunteer_Job__c = job1.Id, Start_Date__c = pastShiftStartDate, Volunteer_Shift__c = pastShift.Id, Status__c = 'Confirmed'));
        hoursToInsert.add(new Volunteer_Hours__c(Contact__c = c.Id, Volunteer_Job__c = job1.Id, Start_Date__c = futureShiftStartDate, Volunteer_Shift__c = futureShift.Id, Status__c = 'Confirmed', Hours_Worked__c  = 2));
        insert hoursToInsert;
    }
    
    @isTest public static void test_batch() {
        Contact c = [Select Id, Volunteer_Hours__c FROM Contact LIMIT 1][0];
        System.assertEquals(20, c.Volunteer_Hours__c );
        Test.startTest();
        AutoCompleter batchable = new AutoCompleter();
        Id processId = Database.executeBatch(batchable); 
        Test.stopTest();
        c = [Select Id, Volunteer_Hours__c FROM Contact LIMIT 1][0];
        System.assertEquals(25, c.Volunteer_Hours__c );
    }
    
    @isTest public static void test_autocompletejob() {
        Test.startTest();
        Id jobId = System.schedule('ScheduleApexClassTest',
                       CRON_EXP, 
                       new AutoCompleter());

        Test.stopTest();
        CronTrigger job = [SELECT Id From CronTrigger WHERE Id =: jobId][0];
        // just asserting that the job exists and we didn't exception.
        System.assert(job.Id == jobId);
        // can't assert that the batch actually ran, because stopTest doesn't actually force it to run
        // see: http://salesforce.stackexchange.com/questions/36806/does-test-stoptest-ensure-a-system-schedule-database-batchable-completes-in-a
    }
}