src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Volunteer_Availability__c</fullName>
        <label>Volunteer Availability</label>
        <picklist>
            <picklistValues>
                <fullName>Weekdays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekends</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Hours__c</fullName>
        <inlineHelpText>Total number of Hours that are Completed. Hours with other status values are not included.</inlineHelpText>
        <label>Volunteer Hours</label>
        <summarizedField>Volunteer_Hours__c.Hours_Worked__c</summarizedField>
        <summaryFilterItems>
            <field>Volunteer_Hours__c.Status__c</field>
            <operation>equals</operation>
            <value>Completed</value>
        </summaryFilterItems>
        <summaryForeignKey>Volunteer_Hours__c.Contact__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Volunteer_Status__c</fullName>
        <label>Volunteer Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Sign Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospective</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volunteer_Hours__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Hours_Worked__c</fullName>
        <label>Hours Worked</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No-Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Sign Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Volunteer_Shift__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Volunteer Shift</label>
        <referenceTo>Volunteer_Shift__c</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Hours</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>HoursID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volunteer_Job__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Volunteer Jobs</relationshipLabel>
        <relationshipName>Volunteer_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Job</label>
    <nameField>
        <label>Volunteer Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volunteer_Shift__c.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <inlineHelpText>How many hours long is the shift?</inlineHelpText>
        <label>Duration (Hours)</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date &amp; Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipLabel>Volunteer Shifts</relationshipLabel>
        <relationshipName>Volunteer_Job_Slots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Shift</label>
    <nameField>
        <displayFormat>Shift-{00000}</displayFormat>
        <label>ShiftID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VOL_CTRL_VolunteersFind_TEST.cls
// Written by David Habib, copyright (c) 2010-2014 DJH Consulting, djhconsulting.com 
// This program is released under the GNU Affero General Public License, Version 3. http://www.gnu.org/licenses/

@isTest
public with sharing class VOL_CTRL_VolunteersFind_TEST {

	//------------------------------------------------------------------------------------------
	// Test Code
	//------------------------------------------------------------------------------------------
    public static testmethod void TestVolunteersFind() {

		// create test data	
		list<Contact> listCon = new list<Contact>();	
		for (integer i = 0; i < 10; i++) {
			listCon.add(new Contact(firstname='test'+i, lastname='test'+i));
			if (i == 1 || i == 3 || i == 5) {
				listCon[i].Volunteer_Status__c = 'Active';
			}
			if (i == 3) {
				listCon[i].Volunteer_Availability__c = 'Morning';
			}			
		}
		insert listCon;
		
        Campaign cmp = new Campaign(recordtypeid=VOL_SharedCode.recordtypeIdVolunteersCampaign, 
        	name='Job Test Campaign', IsActive=true);
        insert cmp;
        Volunteer_Job__c job = new Volunteer_Job__c(name='Job1', campaign__c=cmp.Id);
        insert job;
        Volunteer_Shift__c shift = new Volunteer_Shift__c(Volunteer_Job__c=job.Id, Duration__c=1, Start_Date_Time__c=System.now());
        insert shift;        

        //instantiate the controller 
        VOL_CTRL_VolunteersFind ctrl = new VOL_CTRL_VolunteersFind();
		SoqlListView slv = new SoqlListView();
		slv.pageController = ctrl;        
        
        system.assertNotEquals(null, ctrl);
        system.assertNotEquals(null, ctrl.GetStrSoql());
        system.assertNotEquals(null, ctrl.strFields);
        system.assertNotEquals(null, ctrl.strNameField);
        system.assertNotEquals(null, ctrl.strObjectType);
        system.assertNotEquals(null, ctrl.listSOCampaigns);
        system.assertEquals(null, ctrl.NewItem());
        system.assertEquals(null, ctrl.EditItem(null));
        system.assertNotEquals(null, ctrl.listStrFields);
        system.assertEquals(false, ctrl.hasFilterCriteria);
        
        ctrl.campaignId = cmp.Id;
        ctrl.ChangeCampaign();
        system.assertEquals(2, ctrl.listSOCampaigns.size());
        ctrl.volunteerJobId = job.Id;
        ctrl.ChangeVolunteerJob();
        system.assertEquals(2, ctrl.listSOVolunteerJobs.size());
        system.assertEquals(2, ctrl.listSOVolunteerShifts.size());
        
        ctrl.conFilter.Volunteer_Status__c = 'Active';
        ctrl.ctrlSoqlListView.strAlphaFilter = 't';
        ctrl.Find();
        system.assertEquals(3, ctrl.ctrlSoqlListView.NumberOfItems);
        ctrl.conFilter.Volunteer_Availability__c = 'Morning';
        ctrl.Find();
        system.assertEquals(1, ctrl.ctrlSoqlListView.NumberOfItems);
        system.assertEquals(1, ctrl.ctrlSoqlListView.NumberOfPages);
        system.assertEquals(1, ctrl.ctrlSoqlListView.listSLVObj.size());
        system.assertEquals(10, ctrl.ctrlSoqlListView.cRecordsPerPage);
        ctrl.ctrlSoqlListView.showMoreRecordsPerPage();
        system.assertEquals(20, ctrl.ctrlSoqlListView.cRecordsPerPage);
        system.assertEquals(null, ctrl.ctrlSoqlListView.AlphaFilter());
        system.assertEquals(26, ctrl.ctrlSoqlListView.listAlphaFilters.size());
        ctrl.ctrlSoqlListView.idDeleteItem = null;
        system.assertEquals(null, ctrl.ctrlSoqlListView.DeleteItem());
        ctrl.ctrlSoqlListView.idEditItem = null;
        system.assertEquals(null, ctrl.ctrlSoqlListView.EditItem());        
        system.assertEquals(null, ctrl.ctrlSoqlListView.SortItem());
                
        // test Assign error handling
        ctrl.volunteerJobId = null;
        ctrl.volunteerShiftId = null;
        ctrl.Assign();
                
        // assign 1 volunteer to the job shift
        ctrl.vhAssign.Status__c = 'Confirmed';
        ctrl.vhAssign.Hours_Worked__c = 1;
       	ctrl.ctrlSoqlListView.listSLVObjCurrent[0].checked = true;
       	ctrl.volunteerJobId = job.Id;
        ctrl.volunteerShiftId = shift.Id;
       	ctrl.Assign();
       	list<Volunteer_Hours__c> listVH = [select Id, Contact__c from Volunteer_Hours__c where Volunteer_Job__c = :job.Id];
       	system.assertEquals(1, listVH.size());
       	system.assertEquals(listCon[3].Id, listVH[0].Contact__c); 
        
		// reassign the same volunteer and make sure another volunteer hours record does NOT get created.
       	ctrl.ctrlSoqlListView.listSLVObjCurrent[0].checked = true;
       	ctrl.Assign();
       	listVH = [select Id, Contact__c from Volunteer_Hours__c where Volunteer_Job__c = :job.Id];
       	system.assertEquals(1, listVH.size());
       	system.assertEquals(listCon[3].Id, listVH[0].Contact__c); 
		

    }
}