src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Volunteer_Hours__c</fullName>
        <inlineHelpText>Total number of Hours that are Completed. Hours with other status values are not included.</inlineHelpText>
        <label>Volunteer Hours</label>
        <summarizedField>Volunteer_Hours__c.Hours_Worked__c</summarizedField>
        <summaryFilterItems>
            <field>Volunteer_Hours__c.Status__c</field>
            <operation>equals</operation>
            <value>Completed</value>
        </summaryFilterItems>
        <summaryForeignKey>Volunteer_Hours__c.Contact__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volunteer_Hours__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours_Worked__c</fullName>
        <label>Hours Worked</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Volunteers__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>Defaults to 1. Increase if this person is bringing additional people whom you are not directly tracking as contacts, and won&apos;t be logging individual volunteer hours against.</inlineHelpText>
        <label>Number of Volunteers</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date_Time__c</fullName>
        <inlineHelpText>The actual date &amp; time the volunteer is planning on starting.</inlineHelpText>
        <label>Planned Start Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No-Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Sign Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>System_Note__c</fullName>
        <inlineHelpText>Text information from the system scheduler.</inlineHelpText>
        <label>System Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Volunteer_Recurrence_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Volunteer Recurrence Schedule</label>
        <referenceTo>Volunteer_Recurrence_Schedule__c</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Shift__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Volunteer Shift</label>
        <referenceTo>Volunteer_Shift__c</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Hours</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>HoursID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volunteer_Job__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Volunteers__c</fullName>
        <inlineHelpText>The total number of volunteers whose Hours Status = Completed or Confirmed.</inlineHelpText>
        <label>Number of Volunteers</label>
        <summarizedField>Volunteer_Hours__c.Number_of_Volunteers__c</summarizedField>
        <summaryFilterItems>
            <field>Volunteer_Hours__c.Status__c</field>
            <operation>equals</operation>
            <value>Confirmed, Completed</value>
        </summaryFilterItems>
        <summaryForeignKey>Volunteer_Hours__c.Volunteer_Job__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Volunteer Job</label>
    <nameField>
        <label>Volunteer Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volunteer_Recurrence_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Recurrence Schedules</relationshipLabel>
        <relationshipName>Volunteer_Recurrence_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Days_of_Week__c</fullName>
        <label>Days of Week</label>
        <picklist>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Schedule_End_Date__c</fullName>
        <label>Schedule End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Schedule_Start_Date_Time__c</fullName>
        <label>Schedule Start Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipLabel>Volunteer Recurrence Schedules</relationshipLabel>
        <relationshipName>Volunteer_Recurrence_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weekly_Occurrence__c</fullName>
        <label>Weekly Occurrence</label>
        <picklist>
            <picklistValues>
                <fullName>Every</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1st</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2nd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3rd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4th</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5th</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Volunteer Recurrence Schedule</label>
    <nameField>
        <displayFormat>JRS-{00000}</displayFormat>
        <label>VRS ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Recurrence Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volunteer_Shift__c.object
<CustomObject>
    <fields>
        <fullName>Desired_Number_of_Volunteers__c</fullName>
        <label>Desired # of Volunteers</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <inlineHelpText>How many hours long is the shift?</inlineHelpText>
        <label>Duration (Hours)</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date &amp; Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>System_Note__c</fullName>
        <inlineHelpText>Text information from the system scheduler.</inlineHelpText>
        <label>System Note</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipLabel>Volunteer Shifts</relationshipLabel>
        <relationshipName>Volunteer_Job_Slots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Shift</label>
    <nameField>
        <displayFormat>Shift-{00000}</displayFormat>
        <label>ShiftID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VOL_VRS.cls
/*******************************************************************************************************
* @author David Habib
* @date 11/1/2012
* @description Main class for managing Volunteer Recurrence Schedules (VRS). 
*
* Written by David Habib, copyright (c) 2013 DJH Consulting, djhconsulting.com 
* This program is released under the GNU Affero General Public License, Version 3. http://www.gnu.org/licenses/
********************************************************************************************************/
public with sharing class VOL_VRS {


    //******************************************************************************************************
	// for the specified VRS's, delete all hours that are not completed hours.
	// called from the After Delete VRS trigger.
	public static void DeleteListVRS(list<Volunteer_Recurrence_Schedule__c> listVRS) {
		DeleteListVRS(listVRS, false);
	}
		
    //******************************************************************************************************
	// for the specified VRS's, delete all hours that are not completed hours.
	// called from the After Delete VRS trigger and when we are processing a modified VRS.
	private static void DeleteListVRS(list<Volunteer_Recurrence_Schedule__c> listVRS, boolean fPreserveCanceled) {

		// get a set of the VRS ID's for querying
		set<ID> setVRSId = new set<ID>();
		for (Volunteer_Recurrence_Schedule__c vrs : listVRS) {
			setVRSId.add(vrs.Id);
		}
		
		// get all hours associated with these VRS's that we should delete
		list<Volunteer_Hours__c> listHours = new list<Volunteer_Hours__c>();
		if (fPreserveCanceled) {
			listHours = [select Id from Volunteer_Hours__c  
				where (Status__c <> 'Completed' and Status__c <> 'Canceled' and
					Volunteer_Recurrence_Schedule__c in : setVRSId)];
		} else {
			listHours = [select Id from Volunteer_Hours__c  
				where (Status__c <> 'Completed' and
					Volunteer_Recurrence_Schedule__c in : setVRSId)];			
		}
				
		delete listHours;
	}

   	//******************************************************************************************************
	// given a list of Volunteer recurring schedules, does all the work to delete any hours that
	// no longer match, and creates new hours into the future.
	// called from both the VRS trigger (when the user modifies a specific VRS),
	// as well as from the JRS processing, so new shifts get their hours assigned.
	public static void ProcessListVRS(list<Volunteer_Recurrence_Schedule__c> listVRS) {
		
		// get a set of the VRS ID's for querying
		// also the Job ID's they are associated with
		// also the contact ID's they are associated with
		set<ID> setVRSId = new set<ID>();
		set<ID> setJobId = new set<ID>();
		set<ID> setContactId = new set<ID>();
		for (Volunteer_Recurrence_Schedule__c vrs : listVRS) {
			setVRSId.add(vrs.Id);
			setJobId.add(vrs.Volunteer_Job__c);
			setContactId.add(vrs.Contact__c);
		}
							
		// get all shifts of the jobs these vrs's are associated with
		list<Volunteer_Shift__c> listShift = new list<Volunteer_Shift__c>();
		listShift = [select Id, Duration__c, Start_Date_Time__c, Desired_Number_of_Volunteers__c, 
			Volunteer_Job__c from Volunteer_Shift__c
			where Volunteer_Job__c in :setJobId];
			
		// delete all Hours that aren't completed or canceled.
		DeleteListVRS(listVRS, true);
		
		// construct a map of Job to its associated list of VRS's
		map<ID, list<Volunteer_Recurrence_Schedule__c>> mapJobIdListVRS = new map<ID, list<Volunteer_Recurrence_Schedule__c>>();
		
		// put the VRS's on each job's list
		for (Volunteer_Recurrence_Schedule__c vrs : listVRS) {			
			list<Volunteer_Recurrence_Schedule__c> listVRSforJob = mapJobIdListVRS.get(vrs.Volunteer_Job__c);
			if (listVRSforJob == null) listVRSforJob = new list<Volunteer_Recurrence_Schedule__c>();
			listVRSforJob.add(vrs);
			mapJobIdListVRS.put(vrs.Volunteer_Job__c, listVRSforJob);				
		}
	
		// in order to avoid creating hours that already exist (completed or canceled),
		// create a set of shiftId|contactId tuples, which allows us to quickly see if we
		// already have an hours record for the given shift and contact.
		list<Volunteer_Hours__c> listHoursExisting = [select Id, Volunteer_Job__c, Volunteer_Recurrence_Schedule__c,
			Volunteer_Shift__c, Contact__c from
			Volunteer_Hours__c where Volunteer_Job__c in :setJobId and Contact__c in :setContactId];
		set<string> setShiftIdContactId = new set<string>();
		for (Volunteer_Hours__c hr : listHoursExisting) {
			setShiftIdContactId.add(hr.Volunteer_Shift__c + '|' + hr.Contact__c);
		}

		// create hours for these vrs's for each shift 				
		list<Volunteer_Hours__c> listHoursNew = new list<Volunteer_Hours__c>();
		for (Volunteer_Shift__c shift : listShift) {
			list<Volunteer_Recurrence_Schedule__c> listVRSforJob = mapJobIdListVRS.get(shift.Volunteer_Job__c);
			AssignVRSHours(shift, listVRSforJob, setShiftIdContactId, listHoursNew);
		}
		if (listHoursNew.size() > 0)
			insert listHoursNew;								
		
	}
	
    //******************************************************************************************************
	// for the specified shift, create VolunteerHours records for all volunteers
	// who have a recurring schedule which should include this shift.
	// note that it puts the hours on the provided list, and doesn't actually
	// save them to the database.
	public static void AssignVRSHours(
		Volunteer_Shift__c shift, 
		list<Volunteer_Recurrence_Schedule__c> listVRS, 
		set<string> setShiftIdContactId,
		list<Volunteer_Hours__c> listHoursNew
		) {
			
		if (listVRS == null) return; 

		// Strategy:
		// for the given shift, go through the list of VRS's
		// and create hours for the ones that match.
		
		// we decided not to limit the number of volunteers assigned
		//integer cDesiredVols = 1000;
		//if (shift.Desired_Number_of_Volunteers__c != null) 
		//	cDesiredVols = integer.valueOf(shift.Desired_Number_of_Volunteers__c);
		Date dtShift = shift.Start_Date_Time__c.Date();
		DateTime dtShiftEnd = shift.Start_Date_Time__c.addMinutes(integer.valueOf(shift.Duration__c * 60));
		integer nday = VOL_JRS.nDayOfWeek(dtShift);
		
		for (Volunteer_Recurrence_Schedule__c vrs : listVRS) {
		
			// exit if we've filled all the slots.
			//if (cDesiredVols <= 0) 
				//break;
	
			// for this jrs, what week should we treat this shift as
			integer nweek = VOL_JRS.nWeekOfDate(dtFirstOccurrenceInWeek(vrs, dtShift));
		
			list<boolean> listWhichDays = WhichDaysVRS(vrs);
			list<boolean> listWhichWeeks = WhichWeeksVRS(vrs);
			
			if (vrs.Weekly_Occurrence__c == null)
				continue;
			
			if ((listWhichWeeks[nweek] || 
					vrs.Weekly_Occurrence__c.contains('Every') ||
					(vrs.Weekly_Occurrence__c.contains('Alternate') && alternateWeekVRS(vrs, dtShift))) && 
				listWhichDays[nday] &&
				vrs.Schedule_Start_Date_Time__c != null &&
				dtShift >= vrs.Schedule_Start_Date_Time__c.Date() &&
				(vrs.Schedule_End_Date__c == null || vrs.Schedule_End_Date__c > dtShift)) {
					
				// we need to deal with the person already having hours on this shift
				// that might be completed, or canceled, or web signup.  
				// avoid creating another confirmed record.
				if (setShiftIdContactId.contains(shift.Id + '|' + vrs.Contact__c)) {
					continue;
				}
									
				// only take volunteers whose time fits in the shift time (to handle multiple shifts per day)
				Time tmVRS = vrs.Schedule_Start_Date_Time__c.Time();				
				DateTime dtVRSStart =  datetime.newInstance(dtShift, tmVRS);
				if (dtVRSStart < shift.Start_Date_Time__c  || dtVRSStart >= dtShiftEnd) {
					continue;					
				}	
					
				Volunteer_Hours__c hr = new Volunteer_Hours__c();
				hr.System_Note__c = label.labelVRSHoursCreatedSystemNote + ' ' + vrs.Name + '.';
				hr.Contact__c = vrs.Contact__c;
				hr.Hours_Worked__c = vrs.Duration__c;
				hr.Number_of_Volunteers__c = 1;
				if (vrs.Number_of_Volunteers__c != null && vrs.Number_of_Volunteers__c > 1)
					hr.Number_of_Volunteers__c = vrs.Number_of_Volunteers__c; 
				hr.Start_Date__c = dtShift;
				hr.End_Date__c = dtShift;
				hr.Status__c = (vrs.Volunteer_Hours_Status__c == null ? 'Confirmed' : vrs.Volunteer_Hours_Status__c);
				hr.Volunteer_Job__c = shift.Volunteer_Job__c;
				hr.Volunteer_Shift__c = shift.Id;	
				hr.Volunteer_Recurrence_Schedule__c = vrs.Id;	
				hr.Planned_Start_Date_Time__c = datetime.newInstance(shift.Start_Date_Time__c.date(), vrs.Schedule_Start_Date_Time__c.time());
				hr.Comments__c = vrs.Comments__c;
				listHoursNew.add(hr);
				//cDesiredVols--;
			}			 		
		}
		
		// we let the caller commit the new hours to the db.		
	}

    //******************************************************************************************************
	// returns whether the nweek of the specified date is an alternate week for this schedule
	public static boolean alternateWeekVRS(Volunteer_Recurrence_Schedule__c vrs, Date dt) {
		if (vrs.Schedule_Start_Date_Time__c == null) return false;
		Date dtStart = vrs.Schedule_Start_Date_Time__c.Date().toStartOfWeek();
		Date dtEnd = dt.toStartOfWeek();
		integer cdays = dtStart.daysBetween(dtEnd);
		integer nweeks = (cdays + 1) / 7;
		return math.mod(nweeks, 2) == 0 ? true : false;		
	}		
		
    //******************************************************************************************************
	// returns an array of booleans for which days are on the schedule.
	// note that you should index by nDay (ie, Mon = index 2).
	private static list<boolean> WhichDaysVRS (Volunteer_Recurrence_Schedule__c vrs) {
		list<boolean> listWhichDays = new boolean[] { false, false, false, false, false, false, false, false };
		boolean isSun = VOL_JRS.isSundayFirstOfWeek();
		
		if (vrs.Days_of_Week__c != null) {
			listWhichDays[isSun ? 1 : 7] = vrs.Days_of_Week__c.contains('Sunday');
			listWhichDays[isSun ? 2 : 1] = vrs.Days_of_Week__c.contains('Monday');
			listWhichDays[isSun ? 3 : 2] = vrs.Days_of_Week__c.contains('Tuesday');
			listWhichDays[isSun ? 4 : 3] = vrs.Days_of_Week__c.contains('Wednesday');
			listWhichDays[isSun ? 5 : 4] = vrs.Days_of_Week__c.contains('Thursday');
			listWhichDays[isSun ? 6 : 5] = vrs.Days_of_Week__c.contains('Friday');
			listWhichDays[isSun ? 7 : 6] = vrs.Days_of_Week__c.contains('Saturday');
		}
		return listWhichDays; 
	}

    //******************************************************************************************************
	// returns an array of booleans for which weeks are on the schedule.
	// note that you should index by nWeek (ie, first = index 1).
	private static list<boolean> WhichWeeksVRS(Volunteer_Recurrence_Schedule__c vrs) {
		list<boolean> listWhichWeeks = new boolean[] { false, false, false, false, false, false };
		if (vrs.Weekly_Occurrence__c != null) {
			listWhichWeeks[1] = vrs.Weekly_Occurrence__c.contains('1st');
			listWhichWeeks[2] = vrs.Weekly_Occurrence__c.contains('2nd');
			listWhichWeeks[3] = vrs.Weekly_Occurrence__c.contains('3rd');
			listWhichWeeks[4] = vrs.Weekly_Occurrence__c.contains('4th');
			listWhichWeeks[5] = vrs.Weekly_Occurrence__c.contains('5th');
		}
		return listWhichWeeks;
	}

    //******************************************************************************************************
	// given the current date, return the first date in that week that should be scheduled		
	private static Date dtFirstOccurrenceInWeek(Volunteer_Recurrence_Schedule__c vrs, Date dt) {
		list<boolean> listWhichDays = WhichDaysVRS(vrs);
		integer nday = VOL_JRS.nDayOfWeek(dt);
		integer n;
		for (n = 1; n < nday && n <= 7; n++) { 
			if (listWhichDays[n])
				break;
		}		
		return dt.addDays(n - nday);
	} 	
		
	
}