src/objects/Job_Recurrence_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Days_of_Week__c</fullName>
        <label>Days of Week</label>
        <picklist>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Desired_Number_of_Volunteers__c</fullName>
        <label>Desired Number of Volunteers</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Schedule_Start_Date_Time__c</fullName>
        <label>Schedule Start Date &amp; Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <inlineHelpText>The Job this Recurrence Schedule is for.</inlineHelpText>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipName>Volunteer_Job_Recurrence_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Weekly_Occurrence__c</fullName>
        <label>Weekly Occurrence</label>
        <picklist>
            <picklistValues>
                <fullName>Every</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1st</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2nd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3rd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4th</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5th</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Job Recurrence Schedule</label>
    <nameField>
        <displayFormat>JRS-{00000}</displayFormat>
        <label>JRS ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Recurrence Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volunteer_Job__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Volunteer Jobs</relationshipLabel>
        <relationshipName>Volunteer_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Job</label>
    <nameField>
        <label>Volunteer Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volunteer_Shift__c.object
<CustomObject>
    <fields>
        <fullName>Desired_Number_of_Volunteers__c</fullName>
        <label>Desired # of Volunteers</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <inlineHelpText>How many hours long is the shift?</inlineHelpText>
        <label>Duration (Hours)</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Job_Recurrence_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Automatically set by the system scheduler to show the Job Recurrence Schedule this shift is associated with.</inlineHelpText>
        <label>Job Recurrence Schedule</label>
        <referenceTo>Job_Recurrence_Schedule__c</referenceTo>
        <relationshipLabel>Volunteer Shifts</relationshipLabel>
        <relationshipName>Volunteer_Shifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date &amp; Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipLabel>Volunteer Shifts</relationshipLabel>
        <relationshipName>Volunteer_Job_Slots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Shift</label>
    <nameField>
        <displayFormat>Shift-{00000}</displayFormat>
        <label>ShiftID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VOL_JRS_TEST.cls
// Written by David Habib, copyright (c) 2010-2014 DJH Consulting, djhconsulting.com 
// This program is released under the GNU Affero General Public License, Version 3. http://www.gnu.org/licenses/

@isTest
public with sharing class VOL_JRS_TEST {

    //******************************************************************************************************
    // Test Job Recurrence Schedules    
    public static testmethod void TestJRS() {

		// create test data
        Campaign cmp = new Campaign(recordtypeid=VOL_SharedCode.recordtypeIdVolunteersCampaign, 
        	name='Job Calendar Test Campaign', IsActive=true);
        insert cmp;
        Volunteer_Job__c job = new Volunteer_Job__c(name='Job1', campaign__c=cmp.Id);
        insert job;
        Volunteer_Shift__c shift = new Volunteer_Shift__c(Volunteer_Job__c=job.Id, Duration__c=1, 
        	Start_Date_Time__c=date.newInstance(2012, 1, 1));  // 1/1/2012 was a Sunday
        insert shift;
        Job_Recurrence_Schedule__c jrs = new Job_Recurrence_Schedule__c(Volunteer_Job__c = job.Id);
		jrs.Days_of_Week__c = 'Monday;Wednesday;Friday';
		jrs.Duration__c = 1;

		jrs.Schedule_Start_Date_Time__c = date.newInstance(2012, 1, 1);
		jrs.Weekly_Occurrence__c = 'Every';
		jrs.Desired_Number_of_Volunteers__c = 5;
		insert jrs;
		
		// test Day of Week
		boolean isSun = VOL_JRS.isSundayFirstOfWeek();		
		system.assertEquals(isSun ? 1 : 7, VOL_JRS.nDayOfWeek(date.valueOf('2012-1-1')));
		system.assertEquals(isSun ? 7 : 6, VOL_JRS.nDayOfWeek(date.valueOf('2012-1-7')));
		system.assertEquals(isSun ? 3 : 2, VOL_JRS.nDayOfWeek(date.valueOf('2012-1-31')));
		system.assertEquals(isSun ? 4 : 3, VOL_JRS.nDayOfWeek(date.valueOf('2012-2-1')));
		system.assertEquals(isSun ? 4 : 3, VOL_JRS.nDayOfWeek(date.valueOf('2012-2-29')));
		
		// test dtNthDay
		system.assertEquals(Date.Today(), VOL_JRS.dtNthDay(2012, 1, 1, 1));
		
		// test Every week.
		Date dtNext =  VOL_JRS.dtNextDateforJRS(jrs, date.valueOf(shift.Start_Date_Time__c));
		system.assertEquals(1, VOL_JRS.cWeeksNext(jrs, dtNext, false));
		system.assertEquals(date.valueOf('2012-1-2'), dtNext); 	
		dtNext =  VOL_JRS.dtNextDateforJRS(jrs, dtNext);
		system.assertEquals(date.valueOf('2012-1-4'), dtNext); 	
		dtNext =  VOL_JRS.dtNextDateforJRS(jrs, dtNext);
		system.assertEquals(date.valueOf('2012-1-6'), dtNext); 	
		dtNext =  VOL_JRS.dtNextDateforJRS(jrs, dtNext);
		system.assertEquals(date.valueOf('2012-1-9'), dtNext); 	
		
		// test Alternate weeks.
		jrs.Weekly_Occurrence__c = 'Alternate';
		update jrs;
		system.assertEquals(2, VOL_JRS.cWeeksNext(jrs, dtNext, true));		
		dtNext =  VOL_JRS.dtNextDateforJRS(jrs, dtNext);
		system.assertEquals(date.valueOf('2012-1-11'), dtNext); 	
		dtNext =  VOL_JRS.dtNextDateforJRS(jrs, dtNext);
		system.assertEquals(date.valueOf('2012-1-13'), dtNext); 	
		dtNext =  VOL_JRS.dtNextDateforJRS(jrs, dtNext);
		system.assertEquals(date.valueOf('2012-1-23'), dtNext); 
		
		// test figuring out occurrence of day in month
		system.assertEquals(1, VOL_JRS.nWeekOfDate(date.valueOf('2012-1-1')));
		system.assertEquals(1, VOL_JRS.nWeekOfDate(date.valueOf('2012-1-7')));
		system.assertEquals(2, VOL_JRS.nWeekOfDate(date.valueOf('2012-1-8')));
		system.assertEquals(5, VOL_JRS.nWeekOfDate(date.valueOf('2012-1-29')));
		system.assertEquals(5, VOL_JRS.nWeekOfDate(date.valueOf('2012-1-31')));
		system.assertEquals(1, VOL_JRS.nWeekOfDate(date.valueOf('2012-2-1')));
		system.assertEquals(1, VOL_JRS.nWeekOfDate(date.valueOf('2012-2-4')));
		system.assertEquals(1, VOL_JRS.nWeekOfDate(date.valueOf('2012-2-5')));
		system.assertEquals(5, VOL_JRS.nWeekOfDate(date.valueOf('2012-2-29')));
		system.assertEquals(1, VOL_JRS.nWeekOfDate(date.valueOf('2012-2-6')));
		
		// test Nth week of Month
		jrs.Weekly_Occurrence__c = '3rd';
		update jrs;
		list<boolean> listWhichWeeks = VOL_JRS.WhichWeeksJRS(jrs);
		system.assertEquals(false, listWhichWeeks[0]);
		system.assertEquals(false, listWhichWeeks[1]);
		system.assertEquals(false, listWhichWeeks[2]);
		system.assertEquals(true, listWhichWeeks[3]);
		system.assertEquals(false, listWhichWeeks[4]);
		system.assertEquals(false, listWhichWeeks[5]);

		system.assertEquals(2, VOL_JRS.cWeeksNext(jrs, date.valueOf('2012-1-1'), false));		
		system.assertEquals(2, VOL_JRS.cWeeksNext(jrs, date.valueOf('2012-1-7'), false));		
		system.assertEquals(1, VOL_JRS.cWeeksNext(jrs, date.valueOf('2012-1-8'), false));		
		system.assertEquals(1, VOL_JRS.cWeeksNext(jrs, date.valueOf('2012-1-14'), false));		
		system.assertEquals(5, VOL_JRS.cWeeksNext(jrs, date.valueOf('2012-1-15'), false));		

		dtNext =  VOL_JRS.dtNextDateforJRS(jrs, date.valueOf('2012-1-7')); 
		system.assertEquals(date.valueOf('2012-1-16'), dtNext); 

		jrs.Days_of_Week__c = 'Monday';
		update jrs;
		dtNext =  VOL_JRS.dtNextDateforJRS(jrs, date.valueOf('2012-4-16'));
		system.assertEquals(date.valueOf('2012-5-21'), dtNext); 

		jrs.Days_of_Week__c = 'Wednesday';
		update jrs;
		dtNext =  VOL_JRS.dtNextDateforJRS(jrs, date.valueOf('2012-4-18'));
		system.assertEquals(date.valueOf('2012-5-16'), dtNext); 

		jrs.Weekly_Occurrence__c = '1st';
		jrs.Days_of_Week__c = 'Monday';
		update jrs;
		dtNext =  VOL_JRS.dtNextDateforJRS(jrs, date.valueOf('2012-2-6'));
		system.assertEquals(date.valueOf('2012-3-5'), dtNext); 
		
		jrs.Weekly_Occurrence__c = '2nd;4th;';
		jrs.Days_of_Week__c = 'Sunday';
		update jrs;
		dtNext =  VOL_JRS.dtNextDateforJRS(jrs, date.valueOf('2012-8-1'));
		system.assertEquals(date.valueOf('2012-8-12'), dtNext);  
		
		// test batch calculations
       	VOL_BATCH_Recurrence r = new VOL_BATCH_Recurrence();
    	r.execute(null);	
		
		// test deleting the JRS
		list<Volunteer_Shift__c> listShift = [select Id, Name from Volunteer_Shift__c where Job_Recurrence_Schedule__c = :jrs.Id];
		system.assert(listShift.size() > 0);
		delete jrs;
		listShift = [select Id, Name from Volunteer_Shift__c where Job_Recurrence_Schedule__c = :jrs.Id];
		system.assertEquals(0, listShift.size());
		
    }   

}