src/objects/Job_Recurrence_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Days_of_Week__c</fullName>
        <label>Days of Week</label>
        <picklist>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Description text to copy to shift records created on this schedule.</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Desired_Number_of_Volunteers__c</fullName>
        <label>Desired Number of Volunteers</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Schedule_End_Date__c</fullName>
        <label>Schedule End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Schedule_Start_Date_Time__c</fullName>
        <label>Schedule Start Date &amp; Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <inlineHelpText>The Job this Recurrence Schedule is for.</inlineHelpText>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipName>Volunteer_Job_Recurrence_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Weekly_Occurrence__c</fullName>
        <label>Weekly Occurrence</label>
        <picklist>
            <picklistValues>
                <fullName>Every</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1st</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2nd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3rd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4th</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5th</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Job Recurrence Schedule</label>
    <nameField>
        <displayFormat>JRS-{00000}</displayFormat>
        <label>JRS ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Recurrence Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volunteer_Job__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Number_of_Volunteers__c</fullName>
        <inlineHelpText>The total number of volunteers whose Hours Status = Completed or Confirmed.</inlineHelpText>
        <label>Number of Volunteers</label>
        <summarizedField>Volunteer_Hours__c.Number_of_Volunteers__c</summarizedField>
        <summaryFilterItems>
            <field>Volunteer_Hours__c.Status__c</field>
            <operation>equals</operation>
            <value>Confirmed, Completed</value>
        </summaryFilterItems>
        <summaryForeignKey>Volunteer_Hours__c.Volunteer_Job__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Volunteer Job</label>
    <nameField>
        <label>Volunteer Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volunteer_Recurrence_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Recurrence Schedules</relationshipLabel>
        <relationshipName>Volunteer_Recurrence_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Days_of_Week__c</fullName>
        <label>Days of Week</label>
        <picklist>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Schedule_End_Date__c</fullName>
        <label>Schedule End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Schedule_Start_Date_Time__c</fullName>
        <label>Schedule Start Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipLabel>Volunteer Recurrence Schedules</relationshipLabel>
        <relationshipName>Volunteer_Recurrence_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weekly_Occurrence__c</fullName>
        <label>Weekly Occurrence</label>
        <picklist>
            <picklistValues>
                <fullName>Every</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1st</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2nd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3rd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4th</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5th</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Volunteer Recurrence Schedule</label>
    <nameField>
        <displayFormat>JRS-{00000}</displayFormat>
        <label>VRS ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Recurrence Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volunteer_Shift__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Desired_Number_of_Volunteers__c</fullName>
        <label>Desired # of Volunteers</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <inlineHelpText>How many hours long is the shift?</inlineHelpText>
        <label>Duration (Hours)</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Job_Recurrence_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Automatically set by the system scheduler to show the Job Recurrence Schedule this shift is associated with.</inlineHelpText>
        <label>Job Recurrence Schedule</label>
        <referenceTo>Job_Recurrence_Schedule__c</referenceTo>
        <relationshipLabel>Volunteer Shifts</relationshipLabel>
        <relationshipName>Volunteer_Shifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date &amp; Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>System_Note__c</fullName>
        <inlineHelpText>Text information from the system scheduler.</inlineHelpText>
        <label>System Note</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Volunteers__c</fullName>
        <description>This field is maintained by the VOL_VolunteerHours_ShiftRollups trigger.</description>
        <inlineHelpText>SYSTEM FIELD.  DO NOT EDIT.  The total number of volunteers whose Hours Status = Completed or Confirmed.</inlineHelpText>
        <label>Total Volunteers</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipLabel>Volunteer Shifts</relationshipLabel>
        <relationshipName>Volunteer_Job_Slots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Shift</label>
    <nameField>
        <displayFormat>Shift-{00000}</displayFormat>
        <label>ShiftID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VOL_JRS.cls
/*******************************************************************************************************
* @author David Habib
* @date 11/1/2012
* @description Main class for managing Volunteer Job Recurrence Schedules (JRS). 
*
* Written by David Habib, copyright (c) 2013 DJH Consulting, djhconsulting.com 
* This program is released under the GNU Affero General Public License, Version 3. http://www.gnu.org/licenses/
********************************************************************************************************/
public with sharing class VOL_JRS {

    //******************************************************************************************************
	// for the specified JRS's, delete all shifts that have no committed & completed hours.
	// called from the Before Delete JRS trigger.
	public static void DeleteListJRS(list<Job_Recurrence_Schedule__c> listJRS) {
		
		// get a set of the JRS ID's for querying
		set<ID> setJRSId = new set<ID>();
		for (Job_Recurrence_Schedule__c jrs : listJRS) {
			setJRSId.add(jrs.Id);
		}
		
		// get all shifts associated with these JRS's that we should delete
		list<Volunteer_Shift__c> listShift = new list<Volunteer_Shift__c>();
		listShift = [select Id, Total_Volunteers__c from Volunteer_Shift__c  
			where ((Total_Volunteers__c = null or Total_Volunteers__c = 0) and 
				Job_Recurrence_Schedule__c in : setJRSId)];
		
		delete listShift;
	}

    //******************************************************************************************************
	// given a list of recurring schedules, does all the work to delete any shifts that
	// no longer match, and creates new shifts into the future.
	// called from both the JRS trigger (when the user modifies a specific JRS),
	// as well as from the batch process to reprocess all JRS's.
	// fReviewAllShifts parameter specifies whether called from the trigger on JRS's, in
	// which case we should review all shifts under the JRS, or from the scheduled batch,
	// in which case we only need to be looking to add additional shifts in the future.
	public static void ProcessListJRS(list<Job_Recurrence_Schedule__c> listJRS, boolean fReviewAllShifts) {
		
		// get a set of the JRS ID's for querying
		set<ID> setJRSId = new set<ID>();
		for (Job_Recurrence_Schedule__c jrs : listJRS) {
			setJRSId.add(jrs.Id);
		}
		
		// get all shifts associated with these JRS's
		list<Volunteer_Shift__c> listShift = new list<Volunteer_Shift__c>();
		listShift = [select Id, Start_Date_Time__c, Job_Recurrence_Schedule__c, 
				Total_Volunteers__c, Desired_Number_of_Volunteers__c, Volunteer_Job__c, Description__c, System_Note__c
			from Volunteer_Shift__c where Job_Recurrence_Schedule__c in : setJRSId 
			order by Start_Date_Time__c];
			
		// construct a map of JRS to its associated shifts
		map<ID, list<Volunteer_Shift__c>> mapJRSIdShift = new map<ID, list<Volunteer_Shift__c>>();
		
		// put the Shifts on each JRS's list
		for (Volunteer_Shift__c shift : listShift) {			
			list<Volunteer_Shift__c> listJRSShift = mapJRSIdShift.get(shift.Job_Recurrence_Schedule__c);
			if (listJRSShift == null) listJRSShift = new list<Volunteer_Shift__c>();
			listJRSShift.add(shift);
			mapJRSIdShift.put(shift.Job_Recurrence_Schedule__c, listJRSShift);				
		}

		// lists to hold all the shifts we need to create, delete, and update
		list<Volunteer_Shift__c> listShiftNew = new list<Volunteer_Shift__c>();
		list<Volunteer_Shift__c> listShiftDelete = new list<Volunteer_Shift__c>();
		list<Volunteer_Shift__c> listShiftUpdate = new list<Volunteer_Shift__c>();
		
		// now look at each JRS's shifts, and decide what to do, potentially adding more shifts
		for (Job_Recurrence_Schedule__c jrs : listJRS) {
			list<Volunteer_Shift__c> listJRSShift = mapJRSIdShift.get(jrs.Id);
			if (listJRSShift == null) listJRSShift = new list<Volunteer_Shift__c>(); 
			ProcessJRS(jrs, listJRSShift, listShiftNew, listShiftDelete, listShiftUpdate, fReviewAllShifts);
		}
		
		// commit the work
		if (listShiftNew.size() > 0)
			insert listShiftNew;
		if (listShiftDelete.size() > 0)
			delete listShiftDelete;		
		if (listShiftUpdate.size() > 0)
			update listShiftUpdate;

		// get all Volunteer Recurring Schedules associated with these shift's jobs.
		set<ID> setJobId = new set<ID>();
		for (Volunteer_Shift__c shift : listShiftNew) {
			setJobId.add(shift.Volunteer_Job__c);
		}
		
		// process the VRS's to create hours as needed.
		// we use a future call to avoid hitting statement limits.
		// unfortunately, if we are in our batch job, we aren't allowed to use future!
		if (system.isBatch()) {
			list<Volunteer_Recurrence_Schedule__c> listVRS = new list<Volunteer_Recurrence_Schedule__c>();
			listVRS = [select Id, Name, Contact__c, Schedule_Start_Date_Time__c, Schedule_End_Date__c, Duration__c,
				Weekly_Occurrence__c, Days_Of_Week__c, Volunteer_Job__c, Volunteer_Hours_Status__c, Number_of_Volunteers__c, Comments__c
				from Volunteer_Recurrence_Schedule__c where Volunteer_Job__c in : setJobId];
			VOL_VRS.ProcessListVRS(listVRS);
		} else {
			ProcessListVRSFuture(setJobId);			
		}			
	}
	
    //******************************************************************************************************
	// Process all the VRS's for the set of Job's.  This Future cover was created to avoid
	// hitting apex system statement limits that we would hit if there were many VRS's for a given job.
	@future (callout=false)	
	private static void ProcessListVRSFuture(set<ID> setJobId) {
		
		list<Volunteer_Recurrence_Schedule__c> listVRS = new list<Volunteer_Recurrence_Schedule__c>();
		listVRS = [select Id, Name, Contact__c, Schedule_Start_Date_Time__c, Schedule_End_Date__c, Duration__c,
			Weekly_Occurrence__c, Days_Of_Week__c, Volunteer_Job__c, Volunteer_Hours_Status__c, Number_of_Volunteers__c, Comments__c
			from Volunteer_Recurrence_Schedule__c where Volunteer_Job__c in : setJobId];

		// process the VRS's to create hours as needed.
		VOL_VRS.ProcessListVRS(listVRS);
	}	
	

    //******************************************************************************************************
	// Process a single recurrence schedule, adding new shifts to the passed in list.
	// fReviewAllShifts specifies whether we should verify old shifts still match the schedule.
	private static void ProcessJRS(Job_Recurrence_Schedule__c jrs, 
		list<Volunteer_Shift__c> listJRSShift, // assumes ordered by ascending date
		list<Volunteer_Shift__c> listShiftNew, 
		list<Volunteer_Shift__c> listShiftDelete,
		list<Volunteer_Shift__c> listShiftUpdate,
		boolean fReviewAllShifts ) {
	
		// assume custom setting to specify how far into future shifts should populate to.
		Date dtStop = system.today();
		integer nMonths = 12;
		if (VOL_SharedCode.VolunteersSettings.Recurring_Job_Future_Months__c != null) {
			nMonths = integer.valueOf(VOL_SharedCode.VolunteersSettings.Recurring_Job_Future_Months__c); 
		}
		dtStop = dtStop.addMonths(nMonths);
		
		if (jrs.Schedule_End_Date__c != null)
			dtStop = jrs.Schedule_End_Date__c;
		
		// create a map of date to shift, for quick lookups.
		map<Date, Volunteer_Shift__c> mapDtShift = new map<Date, Volunteer_Shift__c>();
		for (Volunteer_Shift__c shift: listJRSShift) {
			mapDtShift.put(shift.Start_Date_Time__c.date(), shift);
		}
		
		// if fReviewAllShifts, we'll start at the JRS's start date.
		// if !fReviewAllShifts, we'll just start after the latest shift (if we have one).
		Date dtLast;
		if (fReviewAllShifts) {
			dtLast = jrs.Schedule_Start_Date_Time__c.date().addDays(-1);  // -1, so we'll create on start date if appropriate.
		} else if (listJRSShift.size() > 0) {
			dtLast = date.valueOf(listJRSShift[listJRSShift.size() - 1].Start_Date_Time__c);
		} else {
			dtLast = system.Today();			
		}
		
		while (dtLast < dtStop) {
			dtLast = dtNextDateForJRS(jrs, dtLast);
			
			if (dtLast == null || dtLast > dtStop) 
				break;
			
			// see if we already have a shift for that date
			Volunteer_Shift__c shiftExisting = mapDtShift.get(dtLast);
			
			// if we have the shift, update its Job, time and duration
			if (shiftExisting != null) {
				shiftExisting.Duration__c = jrs.Duration__c;
				shiftExisting.Start_Date_Time__c = datetime.newInstance(dtLast, jrs.Schedule_Start_Date_Time__c.time());
				if (jrs.Desired_Number_of_Volunteers__c != null)
					shiftExisting.Desired_Number_of_Volunteers__c = jrs.Desired_Number_of_Volunteers__c;
				if (jrs.Description__c != null)
					shiftExisting.Description__c = jrs.Description__c;
				listShiftUpdate.add(shiftExisting);	
				// also remove the shift from our map, so we'll end up with those to delete.
				mapDtShift.remove(dtLast);			
			} else {
				Volunteer_Shift__c shift = new Volunteer_Shift__c();
				shift.System_Note__c = label.labelJRSShiftCreatedSystemNote + ' ' + jrs.Name + '.';
				shift.Description__c = jrs.Description__c;
				shift.Job_Recurrence_Schedule__c = jrs.Id;
				shift.Duration__c = jrs.Duration__c;
				shift.Volunteer_Job__c = jrs.Volunteer_Job__c;				
				shift.Start_Date_Time__c = datetime.newInstance(dtLast, jrs.Schedule_Start_Date_Time__c.time());
				shift.Desired_Number_of_Volunteers__c = jrs.Desired_Number_of_Volunteers__c;
				listShiftNew.add(shift);
			}
		}
		
		// we've finished identifying shifts to update and those to create.
		// now figure out if there are any to delete or remove from the jrs.
		if (fReviewAllShifts) {
			for (Volunteer_Shift__c shift: mapDtShift.values()) {
				if (shift.Total_Volunteers__c > 0) {
					shift.Job_Recurrence_Schedule__c = null;
					shift.System_Note__c += ' ' + label.labelJRSShiftRemovedSystemNote + ' ' + jrs.Name + '.';					
					listShiftUpdate.add(shift);	
				} else {
					listShiftDelete.add(shift);
				}
			}			
		}		
		
		// we don't commit the shifts, leaving the caller to do it.		
	}
	
    //******************************************************************************************************
	// return the next scheduled date for the given schedule, from the passed in date (exclusive).
	// DOES NOT assume the passed in date is valid for the schedule.
	public static Date dtNextDateforJRS(Job_Recurrence_Schedule__c jrs, Date dt) {
		
		// strategy is to find the first valid nday, and then find its next nweek.
		Date dtFirst = dtFirstOccurrenceInWeek(jrs, dt);
		boolean fAlternate = true;	// we assume the first date passed in is a valid week.
		boolean fValidWeek = validWeek(jrs, dtFirst, fAlternate);  // remember if current date is on valid week.
		
		// if we aren't on a valid week we want to skip to the first nday of the next week.		
		if (!fValidWeek) {
			dt = dtFirst.addDays(6);
		}
		
		integer nDay = nDayOfWeek(dt);
		list<boolean> listWhichDays = WhichDaysJRS(jrs);
		
		for (integer n = nDay; true; ) {
			n++;
			dt = dt.addDays(1);
			
			if (n == 8) {
				n = 1;
				fAlternate = !fAlternate;
			}
			
			if (!listWhichDays[n]) {
				continue;
			}
			
			// we've found the next day.
			// now find the correct week.
			if ((fValidWeek && n > nDay) || validWeek(jrs, dt, fAlternate)) {
				break;
			}
			integer cweeks = cWeeksNext(jrs, dt, fAlternate);
			dt = dt.addDays(cweeks * 7);
			break;			
		}
		
		return dt;		
	}
	
    //******************************************************************************************************
	// returns an array of booleans for which days are on the schedule.
	// note that you should index by nDay (ie, Mon = index 2).
	private static list<boolean> WhichDaysJRS (Job_Recurrence_Schedule__c jrs) {
		list<boolean> listWhichDays = new boolean[] { false, false, false, false, false, false, false, false };
		boolean isSun = isSundayFirstOfWeek();
		
		if (jrs.Days_of_Week__c != null) {
			listWhichDays[isSun ? 1 : 7] = jrs.Days_of_Week__c.contains('Sunday');
			listWhichDays[isSun ? 2 : 1] = jrs.Days_of_Week__c.contains('Monday');
			listWhichDays[isSun ? 3 : 2] = jrs.Days_of_Week__c.contains('Tuesday');
			listWhichDays[isSun ? 4 : 3] = jrs.Days_of_Week__c.contains('Wednesday');
			listWhichDays[isSun ? 5 : 4] = jrs.Days_of_Week__c.contains('Thursday');
			listWhichDays[isSun ? 6 : 5] = jrs.Days_of_Week__c.contains('Friday');
			listWhichDays[isSun ? 7 : 6] = jrs.Days_of_Week__c.contains('Saturday');
		}
		return listWhichDays; 
	}

    //******************************************************************************************************
	// returns whether Sunday is the first day of the week (US), or not (Europe goes with Monday).
	public static boolean isSundayFirstOfWeek() {
		Date dt = date.valueOf('2012-1-1');	// Jan 1st 2012 was a Sunday!
		return (dt == dt.toStartOfWeek());	
	}
	
    //******************************************************************************************************
	// returns an array of booleans for which weeks are on the schedule.
	// note that you should index by nWeek (ie, first = index 1).
	public static list<boolean> WhichWeeksJRS(Job_Recurrence_Schedule__c jrs) { 
		list<boolean> listWhichWeeks = new boolean[] { false, false, false, false, false, false };
		if (jrs.Weekly_Occurrence__c != null) {
			listWhichWeeks[1] = jrs.Weekly_Occurrence__c.contains('1st');
			listWhichWeeks[2] = jrs.Weekly_Occurrence__c.contains('2nd');
			listWhichWeeks[3] = jrs.Weekly_Occurrence__c.contains('3rd');
			listWhichWeeks[4] = jrs.Weekly_Occurrence__c.contains('4th');
			listWhichWeeks[5] = jrs.Weekly_Occurrence__c.contains('5th');
		}
		return listWhichWeeks;
	}   


    //******************************************************************************************************
	// given the current date, return the first date in that week that should be scheduled		
	private static Date dtFirstOccurrenceInWeek(Job_Recurrence_Schedule__c jrs, Date dt) {
		list<boolean> listWhichDays = WhichDaysJRS(jrs);
		integer nday = nDayOfWeek(dt);
		integer n;
		for (n = 1; n < nday; n++) {
			if (listWhichDays[n])
				break;
		}		
		return dt.addDays(n - nday);
	} 	
		
    //******************************************************************************************************
	// return the occurrence of the day in the month (ie, 1 first - 5 fifth)
	public static integer nWeekOfDate(Date dt) {
		return ((dt.day() - 1) / 7) + 1;
	}
	
    //******************************************************************************************************
	// return the date of the nth day in the nth week of the provided month and year
	// ie, return the 2nd Friday of Feb 2012.  
	// nday: 1 - 7 (implying Sun - Sat)
	// nweek: 1 - 5 (implying first - fifth)
	// NOTE: Logic was flawed in this routine, but it is not actually used,
	// so it has been stubbed out to just return Today.
	public static Date dtNthDay(integer year, integer month, integer nday, integer nweek) {
		return Date.Today();
	} 
	
    //******************************************************************************************************
	// returns an integer 1 - 7, representing the day of the week.
	public static integer nDayOfWeek(Date dt) {
		return (dt.toStartOfWeek().daysBetween(dt) + 1);		
	}
	
    //******************************************************************************************************
	// returns whether the nweek of the specified date is valid for this schedule
	private static boolean validWeek(Job_Recurrence_Schedule__c jrs, Date dt, boolean fAlternate) {
		integer nweek = nWeekOfDate(dt);
		list<boolean> listWhichWeeks = WhichWeeksJRS(jrs);
		if (jrs.Weekly_Occurrence__c == null)
			return false;
		else if (listWhichWeeks[nweek] || jrs.Weekly_Occurrence__c.contains('Every'))
			return true;
		else if (fAlternate && jrs.Weekly_Occurrence__c.contains('Alternate'))
			return true;
		else
			return false;
	}	
	
    //******************************************************************************************************
	// returns how many weeks until the next recurrence on the schedule
	public static integer cWeeksNext(Job_Recurrence_Schedule__c jrs, Date dt, boolean fAlternate) {
		if (jrs.Weekly_Occurrence__c == null) {
			// treat empty as every week, so we avoid infinite loops.
			return 1;
		} else if (jrs.Weekly_Occurrence__c.contains('Every')) { 
			return 1;
		} else if (jrs.Weekly_Occurrence__c.contains('Alternate')) {
			return fAlternate ? 2 : 1;
		} else {
			list<boolean> listWhichWeeks = WhichWeeksJRS(jrs);
			integer nweek = nWeekOfDate(dt);
			integer cweeks = 0;
			
			for (integer n = nweek + 1; true; n++) {
				if (n == 6) {
					Date dtEndOfMonth = dt.toStartOfMonth().addMonths(1).addDays(-1);
					cweeks = (dt.daysBetween(dtEndOfMonth) / 7) + 1;
					nweek = 1;
					n = 0;
					continue;
				}
				if (listWhichWeeks[n]) { 
					return (n - nweek + cweeks);
				}
			}
		}
		return 0;
	}  
	
}