src/objects/Volunteer_Hours__c.object
<CustomObject>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Volunteer_Shift__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Volunteer Shift</label>
        <referenceTo>Volunteer_Shift__c</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Hours</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>HoursID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volunteer_Job__c.object
<CustomObject>
    <label>Volunteer Job</label>
    <nameField>
        <label>Volunteer Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volunteer_Shift__c.object
<CustomObject>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipLabel>Volunteer Shifts</relationshipLabel>
        <relationshipName>Volunteer_Job_Slots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Shift</label>
    <nameField>
        <displayFormat>Shift-{00000}</displayFormat>
        <label>ShiftID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FeatureManagementService.cls
public with sharing class FeatureManagementService {
    List<FeatureParam> recordCounts = new List<FeatureParam>{
        new FeatureParam('JobsAllTime').withRecordCount(Volunteer_Job__c.SObjectType, ''),
        new FeatureParam('JobsLastYear').withRecordCount(Volunteer_Job__c.SObjectType, 'CreatedDate = LAST_YEAR'),
        new FeatureParam('JobsThisYear').withRecordCount(Volunteer_Job__c.SObjectType, 'CreatedDate < THIS_YEAR')
    };

    List<FeatureParam> fieldCounts = new List<FeatureParam>{
        new FeatureParam('JobsCustomFields').withCustomFieldCount(Volunteer_Job__c.SObjectType),
        new FeatureParam('ShiftsCustomFields').withCustomFieldCount(Volunteer_Shift__c.SObjectType),
        new FeatureParam('HoursCustomFields').withCustomFieldCount(Volunteer_Hours__c.SObjectType)
    };

    public FeatureManagementService() {}

    public void updateRecordCounts() {
        for (FeatureParam recordCount : recordCounts) {
            recordCount.send();
        }

    }

    public void updateCustomFieldCounts() {
        for (FeatureParam fieldCount : fieldCounts) {
            fieldCount.send();
        }

    }
}