src/objects/Volunteer_Hours__c.object
<CustomObject>
    <fields>
        <fullName>Shift_Start_Date_Time__c</fullName>
        <formula>Volunteer_Shift__r.Start_Date_Time__c</formula>
        <label>Shift Start Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No-Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Sign Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Volunteer Hours</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>HoursID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VOL_AutoCompleter.cls
global class VOL_AutoCompleter implements Schedulable {
    global void execute(SchedulableContext sc) {
        List<Volunteer_Hours__c> hoursToProcess = [SELECT Id FROM Volunteer_Hours__c 
                                                                 WHERE Status__c = 'Confirmed'
                                                                 AND Shift_Start_Date_Time__c < TODAY
                                                                 AND Do_Not_AutoComplete__c != true];
        
        for(Volunteer_Hours__c hr : hoursToProcess) {
            hr.Status__c = 'Completed';
        }
        
        update hoursToProcess;
    }
}