src/objects/Volunteer_Job__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Volunteer Jobs</relationshipLabel>
        <relationshipName>Volunteer_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Job</label>
    <nameField>
        <label>Volunteer Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UTIL_UnitTest.cls
@IsTest
public class UTIL_UnitTest {
    public static User guestSiteUser {
        get {
            if (guestSiteUser == null) {
                guestSiteUser = findGuestSiteUser();
            }
            return guestSiteUser;
        }
        private set;
    }

    private static User findGuestSiteUser() {
        List<User> guestSiteUsers = [Select Username, UserType, Name, IsActive, Id From User where IsActive = true and UserType = 'Guest' and
        Name like '%Site Guest User%'];

        if (guestSiteUsers.isEmpty()) {
            return null;
        }

        return guestSiteUsers[0];
    }

    public static Map<Id, SObject> generateData() {
        Map<Id, SObject> sObjectById = new Map<Id, SObject>();
        DateTime now = System.now();

        Campaign campaignRecord = createCampaign('Spring Garden Party ' + now);
        insert campaignRecord;
        sObjectById.put(campaignRecord.Id, campaignRecord);

        Volunteer_Job__c volunteerJob = createJob('Classroom Helper ' + now, campaignRecord.Id);
        insert volunteerJob;
        sObjectById.put(volunteerJob.Id, volunteerJob);

        Contact contactRecord = createContact('Helper ' + now);
        insert contactRecord;
        sObjectById.put(contactRecord.Id, contactRecord);

        return sObjectById;
    }

    public static Campaign createCampaign(String name) {
        return new Campaign(
            RecordTypeId = VOL_SharedCode.recordtypeIdVolunteersCampaign,
            Name = name,
            IsActive = true
        );
    }

    public static Volunteer_Job__c createJob(String name, Id campaignId) {
        return new Volunteer_Job__c(
            Name = name,
            Campaign__c = campaignId
        );
    }

    public static Contact createContact(String lastName) {
        return new Contact(
            FirstName = 'Andy',
            LastName = lastName);
    }
}